# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: mongo-service-ext
  namespace: default
spec:
  selector:
    app: mongodb
  type: LoadBalancer
  ports:
  - name: mongo-service-ext
    protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30000
